### PR TITLE
Initial tests for the Metronome component

### PR DESCRIPTION
**Pull request by flynnn231**
Added some unit tests to the metronome. Here is an example:

image

We also need to manually test the sound played by the metronome, taking beats per minute into consideration.

### CODE REVIEW

**Review by elijaholan — APPROVED** [review]
Looks good, however, we need to add describe blocks to make these tests a bit more organised.

**Review by Jsimpada — APPROVED** [review]
No issues, and all tests for the Metronome are passing. Nice!

**Review by melissalupu — APPROVED** [review]
Similar to Elijah's comment, make sure that you add some describe blocks, like the ones demonstrated in the previous pull request.

**Review by brunogrcsada — APPROVED** [review]
Nice PR, looks great, make sure you add the 'test' tag next time you make a request. I also agrees with the others that the tests should be a bit more organised. We'll address that in the next meeting :+1:

**Pull request merged**
