### PR TITLE
Added coveralls upload for code coverage (GitHub Action)

### PR DESCRIPTION
**Pull request by Jsimpada**
### Screenshot
image

Every time code is pushed or a pull request is made, code coverage will be uploaded to coveralls.io, allowing us to display a badge on the README:

image

(We are aiming for 100% code coverage!)

### CODE REVIEW

**Review by flynnn231 — APPROVED** [review]
This is a great tool Jaheim, thank you for setting it up with our repo :+1:

**Review by elijaholan — APPROVED** [review]
Nice! The badge will look great on the README

**Review by melissalupu — APPROVED** [review]
Looks good, we need to make a meeting with Bruno to put the badge on the README

**Review by brunogrcsada — APPROVED** [review]
Great work Jaheim, I need to hire you for my startup :o

**Pull request merged**
