### PR TITLE
Added a set of testable helper functions

### PR DESCRIPTION
**Pull request by elijaholan**
This is available at src/helpers.js:

image

To help with testing logic, code was refactored into functions with specific functionality. The example above allows a regular keyboard key such as 'q' to be converted to its respective key ('F3'). This will be displayed in the bubble underneath the keyboard. A few initial tests for the convertToNote () function were also added.

This pull request also fixes an issue targeting the metronome, where using 0 as an input value would cause the metronome to play beats at an insanely high speed. The new helper function sanitiseBeat() helps ensure that the correct values are used for the metronome.

### CODE REVIEW

**Review by brunogrcsada — APPROVED** [review]
Lovely peer-coding session! This pull request fixes quite a few issues brought up previously:
Closes #34 Closes #36

**Review by melissalupu — APPROVED** [review]
This is a lot easier to test, thank you :)

**Review by Jsimpada — APPROVED** [review]
All good, CI tests are passing, nice one.

**Review by flynnn231 — APPROVED** [review]
Looks good!

**Pull request merged**
